import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs';
import "./globals.css";
import { MantineProvider } from '@mantine/core';
import Navbar from "@/components/navbar";
import { jetBrainsMono } from "./font";

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider afterSignOutUrl={"/"}>
      <html lang="en">
        <body className={`${jetBrainsMono.variable} font-sans`}>
          <Navbar></Navbar>
          <MantineProvider>
            {children}
          </MantineProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
